name: geofence_foreground_service
description: A Flutter project that creates a foreground service to handle geofencing.
version: 1.1.3
repository: https://github.com/Basel-525k/geofence_foreground_service
license: Apache-2.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  latlng: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.f2fk.geofence_foreground_service
        pluginClass: GeofenceForegroundServicePlugin
      ios:
        pluginClass: GeofenceForegroundServicePlugin